### ISSUE TITLE
Rate estimation: Faulty logic in muonType selection?

### ISSUE THREAD

**Issue by tempse** [cms-l1-dpg/L1MenuTools#33]
Hi @ahenckel, @wang-hui, @jheikkil, @elfontan, all,

Do we know if the following L353 contains a bug? 
https://github.com/cms-l1-dpg/L1MenuTools/blob/c7bd84c5cd08c2add972fce387ebf5fcdb4c02d2/rate-estimation/include/L1AlgoFactory.C#L344-L353

The logic contradicts the comment that is written a few lines above (L347).

I was just made aware of this peculiarity and wanted to share it with you. So far, no concrete error behavior has come to my attention, but it will be good to keep this in mind.

Thanks, Sebastian

**Comment by jheikkil** [comment]
@ahenckel : Would you have time to take a look?

**Comment by jheikkil** [comment]
Solved with the above PR - thank you everybody!

**Comment by jheikkil** [comment]
Closing!
