### ISSUE TITLE
Follow-up on PR #62

### ISSUE THREAD

**Issue by dildick** [cms-l1-dpg/L1MenuTools#65]
I was working with our team to try to get the menu tools to run on signal samples. My initial implementation of shower type may be problematic.

```
{# Template for signal type conditions like centrality or muon showers #}
{# MuonShowerType from L1TNtuples: kInvalid, kOneNominal,kOneTight, kTwoLoose #}
{# See in: L1Trigger/L1TNtuples/interface/L1AnalysisL1UpgradeDataFormat.h #}
```

A Regional Muon Shower, or Muon Shower can be (1) nominal or (2) nominal+tight. A tight shower is always also a nominal shower. The enum implementation won't allow that.

@arnobaer Do you have a suggestion how to update the ntuplizer and the menu tools?

**Comment by elfontan** [comment]
The final PR for the hadronic muon showers trigger is: https://github.com/cms-l1-dpg/L1MenuTools/pull/66.
Previous related PRs:
- https://github.com/cms-l1-dpg/L1MenuTools/pull/62
- https://github.com/cms-l1-dpg/L1MenuTools/pull/64
